name: landmark_assignment
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  lottie: ^3.1.0
  dio: ^5.4.1
  cached_network_image: ^3.3.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  mocktail: ^0.2.0

flutter: 
  uses-material-design: true
  assets:
    - assets/lottie_files/

